<a href="https://colab.research.google.com/github/sanjayvs600/datamining/blob/main/Copy_of_Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

from google.colab import drive
drive.mount('/content/drive')

In [1]:
import numpy as np
import pandas as pd



In [3]:
file_path='/content/drive/MyDrive/DM/DM.csv'
df=pd.read_csv(file_path)

print(df)

    Trip ID       Destination  Start date    End date  Duration (days)  \
0         1        London, UK  05-01-2023  05-08-2023              7.0   
1         2  Phuket, Thailand   6/15/2023   6/20/2023              5.0   
2         3   Bali, Indonesia  07-01-2023  07-08-2023              7.0   
3         4     New York, USA   8/15/2023   8/29/2023             14.0   
4         5      Tokyo, Japan  09-10-2023   9/17/2023              7.0   
..      ...               ...         ...         ...              ...   
94       95             Paris   6/15/2022   6/20/2022              5.0   
95       96             Tokyo  09-01-2022  09-10-2022              9.0   
96       97            Sydney  11/23/2022  12-02-2022              9.0   
97       98            London   2/14/2023   2/19/2023              5.0   
98       99          New York  05-08-2023   5/14/2023              6.0   

    Traveler name  Traveler age Traveler gender Traveler nationality  \
0      John Smith          35.0        

In [4]:
df.isnull().sum()

Trip ID                 0
Destination             1
Start date              1
End date                1
Duration (days)         1
Traveler name           1
Traveler age            1
Traveler gender         1
Traveler nationality    1
Accommodation type      1
Accommodation cost      1
Transportation type     2
Transportation cost     2
dtype: int64

In [9]:
df.duplicated().sum()

0

In [7]:
import pandas as pd
column_name = 'Duration (days)'
try:
    df[column_name] = pd.to_datetime(df[column_name])
    sort_value = np.sort(df[column_name].values)
    print(sort_value)
except ValueError:
    print("Conversion failed: The column contains values that can't be interpreted as dates.")

['1970-01-01T00:00:00.000000005' '1970-01-01T00:00:00.000000005'
 '1970-01-01T00:00:00.000000005' '1970-01-01T00:00:00.000000005'
 '1970-01-01T00:00:00.000000005' '1970-01-01T00:00:00.000000006'
 '1970-01-01T00:00:00.000000006' '1970-01-01T00:00:00.000000006'
 '1970-01-01T00:00:00.000000006' '1970-01-01T00:00:00.000000006'
 '1970-01-01T00:00:00.000000006' '1970-01-01T00:00:00.000000006'
 '1970-01-01T00:00:00.000000006' '1970-01-01T00:00:00.000000006'
 '1970-01-01T00:00:00.000000006' '1970-01-01T00:00:00.000000006'
 '1970-01-01T00:00:00.000000006' '1970-01-01T00:00:00.000000007'
 '1970-01-01T00:00:00.000000007' '1970-01-01T00:00:00.000000007'
 '1970-01-01T00:00:00.000000007' '1970-01-01T00:00:00.000000007'
 '1970-01-01T00:00:00.000000007' '1970-01-01T00:00:00.000000007'
 '1970-01-01T00:00:00.000000007' '1970-01-01T00:00:00.000000007'
 '1970-01-01T00:00:00.000000007' '1970-01-01T00:00:00.000000007'
 '1970-01-01T00:00:00.000000007' '1970-01-01T00:00:00.000000007'
 '1970-01-01T00:00:00.000

In [8]:

import pandas as pd
import numpy as np

num_bins = 15
bin_size = len(sort_value) // num_bins
if bin_size == 0:
    num_bins = 1
bin_mean = np.zeros(num_bins)
bin_boundaries = np.zeros((num_bins, bin_size))
bin_median = np.zeros(num_bins)

for i in range(num_bins):
    start = i * bin_size
    end = (i + 1) * bin_size

    timestamps = (sort_value[start:end] - np.datetime64('1970-01-01T00:00:00Z')) / np.timedelta64(1, 's')
    bin_mean[i] = np.mean(timestamps)

    bin_mean_datetime = pd.to_datetime(bin_mean[i] * 1e9)
    print("Bin mean (datetime):", bin_mean_datetime)

    for j in range(bin_size):
        if (sort_value[start + j] - sort_value[start]) < (sort_value[start + bin_size - 1] - sort_value[start + j]):
            bin_boundaries[i, j] = sort_value[start]
        else:
            bin_boundaries[i, j] = sort_value[start + bin_size - 1]

    timestamps_median = (sort_value[start:end] - np.datetime64('1970-01-01T00:00:00Z')) / np.timedelta64(1, 's')
    bin_median[i] = np.median(timestamps_median)
print("Bin median:\n", bin_median)
print("Bin boundaries:\n", bin_boundaries)
print("Bin mean:\n", bin_mean)

Bin mean (datetime): 1970-01-01 00:00:00.000000005
Bin mean (datetime): 1970-01-01 00:00:00.000000006
Bin mean (datetime): 1970-01-01 00:00:00.000000006
Bin mean (datetime): 1970-01-01 00:00:00.000000006
Bin mean (datetime): 1970-01-01 00:00:00.000000006
Bin mean (datetime): 1970-01-01 00:00:00.000000006
Bin mean (datetime): 1970-01-01 00:00:00.000000006
Bin mean (datetime): 1970-01-01 00:00:00.000000006
Bin mean (datetime): 1970-01-01 00:00:00.000000006
Bin mean (datetime): 1970-01-01 00:00:00.000000007
Bin mean (datetime): 1970-01-01 00:00:00.000000008
Bin mean (datetime): 1970-01-01 00:00:00.000000008
Bin mean (datetime): 1970-01-01 00:00:00.000000008
Bin mean (datetime): 1970-01-01 00:00:00.000000009
Bin mean (datetime): 1970-01-01 00:00:00.000000009
Bin median:
 [5.0e-09 6.0e-09 6.0e-09 7.0e-09 7.0e-09 7.0e-09 7.0e-09 7.0e-09 7.0e-09
 7.5e-09 8.0e-09 8.0e-09 9.0e-09 9.0e-09 1.0e-08]
Bin boundaries:
 [[ 5.  5.  5.  5.  5.  6.]
 [ 6.  6.  6.  6.  6.  6.]
 [ 6.  6.  6.  6.  6.  7.]
 

<ipython-input-8-ace7bba07606>:16: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
  timestamps = (sort_value[start:end] - np.datetime64('1970-01-01T00:00:00Z')) / np.timedelta64(1, 's')
<ipython-input-8-ace7bba07606>:28: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
  timestamps_median = (sort_value[start:end] - np.datetime64('1970-01-01T00:00:00Z')) / np.timedelta64(1, 's')
